### ISSUE TITLE
Search box covers whole first line

### ISSUE THREAD

**Issue by tyskan** [getsmap/smap-responsive#134]
after pull the search box is stretched across the whole window - css problem?

**Comment by johanlahti** [comment]
Shouldn't be… however, it should cover the whole width on small screens when the search entry is focused.

Try pulling the code again and if not helping, do a revert of your files (make sure you commit first :smile:  )

**Comment by johanlahti** [comment]
I can not recreate this. Re-open if I'm wrong.
