### ISSUE TITLE
IE 10 - language is english and locate not working.

### ISSUE THREAD

**Issue by tyskan** [getsmap/smap-responsive#135]

**Comment by tyskan** [comment]
hej! It could be our version of IE as well? we have 10.0.9200.17183.
geolocation works with malmös version but not with ours....

**Comment by johanlahti** [comment]
I will check, but I feel like I've seen this problem before…

**Comment by johanlahti** [comment]
Yes, the fallback language was english. I set it to Swedish now (forgot to label this ticket in the commit though :) ). I close the issue.

**Comment by johanlahti** [comment]
However, locate should work. Forgot to check that. Open this issue again if noticed.
