### ISSUE TITLE
Get hidden layers/tools

### ISSUE THREAD

**Issue by johanlahti** [getsmap/smap-responsive#139]
Add more layers to the map (config) if you are within the Malmö network.

**Comment by johanlahti** [comment]
Just need to look over the layers and names returned by the scripts: @stinamunsin will do that. Otherwise implemented.

**Comment by stinamunsin** [comment]
Klar

**Comment by johanlahti** [comment]
Grejt! Jag har lagt in lagren så att de returneras från server-sidan.
