### ISSUE TITLE
Print

### ISSUE THREAD

**Issue by stinamunsin** [getsmap/smap-responsive#141]
Om man kryssar i teckenförklaring funkar inte utskriften om man har Stadskartan som bakgrund. 
Om man har ex ortofoto som bakgrund funkar det. Men man får bara teckenförklaring vid stående A4 och A3 (fast mitt på bilden) inte A5. Vid liggande funkar endast A3.

Beskrivningen till kartan funkar men texten hamnar på kartan vid A5 och stående A4 om man har en lång beskrivning.

**Comment by johanlahti** [comment]
Jag har uppdaterat config-filen för MapFish print ```leaflet_print.yaml ``` med ```absoluteX``` och ```absoluteY```-värden som gör att de hamnar inom papperets utbredning. Tidigare hamnade de utanför.
