### ISSUE TITLE
Print NonTiledLayer dosen´t work

### ISSUE THREAD

**Issue by stinamunsin** [getsmap/smap-responsive#142]
Det funkar inte att skriva ut NonTiledLayer. Det går bra med TileLayer (cykelvägar).

**Comment by johanlahti** [comment]
Should be working now. For all NonTiledLayers I force put a printLayer which is a clone of existing layer but with init "L.TileLayer.WMS". This layer is temporarily added (original temporarily removed) to the map during print and removed after print (and original added back).
