### ISSUE TITLE
Länkar skapade efter Rita och mät blir för långa

### ISSUE THREAD

**Issue by stinamunsin** [getsmap/smap-responsive#143]
och då funkar inte länken. Det räcker med en linje och en yta.

**Comment by johanlahti** [comment]
URL:en sparar GeoJSON som tar ganska mycket plats. Det kommer redan nu en varning när länken blir längre än vad som är acceptabelt för vissa webbläsare.

Modulen är förberedd på att spara och hämta data med andra metoder. I nästa version kan vi implementera att ett id skickas med istället som länkar till en rad i en databastabell. Jag skapar en sån issue redan nu.

Hur tycker du/ni vi ska göra det tydligare att länken är för lång? Ska den blockeras helt? Ska man varnas innan man börjar redigera? Eller ska vi helt enkelt låta det vara som det är?

**Comment by stinamunsin** [comment]
Jag tycker att man antingen blir varnad när strängen blivit för lång eller att man inte ska kunna kopiera en för lång stäng. Det kan ju hända att man missar varningstexten, som jag gjorde, och då funkar inget och man blir irriterad.

**Comment by johanlahti** [comment]
Jag gör antingen URL:en disablad eller en ful-alert när den är för lång så blir det tydligare.

**Comment by ulfmin** [comment]
Kan man göra den disablad och då få upp en fulalert

Från: Johan Lahti [mailto:notifications@github.com]
Skickat: den 14 januari 2015 16:17
Till: getsmap/smap-responsive
Kopia: Ulf Minör
Ämne: Re: [smap-responsive] Länkar skapade efter Rita och mät blir för långa (#143)


Jag gör antingen URL:en disablad eller en ful-alert när den är för lång så blir det tydligare.

**Comment by johanlahti** [comment]
Du menar både fulalert och disablad? Jag fixar det!

**Comment by johanlahti** [comment]
Jag har testat och tror att alert ovanpå disablat blir för mycket. Ni får avgöra.

**Comment by johanlahti** [comment]
Jag lyckas rita en polygon med 25 noder och en linje med 27 noder utan att stöta i gränsen för Internet Explorer. Däremot endast 3 markörer får plats innan länken blir för lång. Kanske ska fundera på ett smartare sätt att spara punkterna.

**Comment by johanlahti** [comment]
Jag har tagit bort onödiga attribut och avrundar koordinater till fem decimaler och har då lyckats pressa ner det till 11 markörer utan att ändra formatet (GeoJSON).

**Comment by johanlahti** [comment]
Jag har även lagt in en hemmabyggd komprimeringsmetod och lyckas då skapa 18 markörer eller en polygon med 62 noder. Kanske hälften så många markörer om man skriver en text för varje.

**Comment by johanlahti** [comment]
Would be grateful if someone could test this link on IE9 and up: http://kartor.malmo.se/rest/leaf/1.0-dev/?zoom=11&center=12.96215,55.63168&ol=measurelayer&bl=stadskartan&config=../configs-1.0/malmo_atlas.js&sel=%7B%22measurelayer%22%3A%7B%22vals%22%3A%5B48%5D%2C%22key%22%3A%22id%22%7D%7D&md=url%2C%7B:t:%22FeatureCollection%22%2C:fs:%5B%7B:t::F:%2C:p%7B%22id%22:30%2C:mt::%22Testar%22%7D%2C:g:%7B:t:%22Polygon%22%2C:c:%5B%5B%5B12.9467%2C55.55544%5D%2C%5B12.9467%2C55.59658%5D%2C%5B13.02704%2C55.59658%5D%2C%5B13.02704%2C55.55544%5D%2C%5B12.9467%2C55.55544%5D%2C%5B12.9467%2C55.55544%5D%5D:--:%7D%2C%7B:t::F:%2C:p%7B%22id%22:48%2C:mt::%22Testar%22%2C%22popupIsOpen%22:true%7D%2C:g:%7B:t::P:%2C:c:%5B13.0703%2C55.59115:--:%7D%2C%7B:t::F:%2C:p%7B%22id%22:53%2C:mt::%22%22%7D%2C:g:%7B:t::P:%2C:c:%5B13.09296%2C55.55078:--:%7D%2C%7B:t::F:%2C:p%7B%22id%22:69%2C:mt::%22%22%7D%2C:g:%7B:t:%22LineString%22%2C:c:%5B%5B12.98241%2C55.62218%5D%2C%5B13.11356%2C55.65357%5D%2C%5B13.15475%2C55.63807%5D%2C%5B13.13828%2C55.58921%5D:--:%7D:--:

**Comment by johanlahti** [comment]
Would be grateful if someone could test this link in IE9 and up (3 markers should appear, 1 polyline and 1 polygon with an opened popup on the marker saying "En markör"):

http://kartor.malmo.se/rest/leaf/1.0-dev/?zoom=13&center=12.96327,55.59154&ol=measurelayer&bl=stadskartan&config=../configs-1.0/malmo_atlas.js&sel=%7B%22measurelayer%22%3A%7B%22vals%22%3A%5B38%5D%2C%22key%22%3A%22id%22%7D%7D&md=url%2C%7B:t:%22FeatureCollection%22%2C:fs:%5B%7B:t::F:%2C:p%7B%22id%22:29%2C:mt::%22%22%7D%2C:g:%7B:t::P:%2C:c:%5B13.00438%2C55.60376%5D%7D%7D%2C%7B:t::F:%2C:p%7B%22id%22:35%2C:mt::%22%22%7D%2C:g:%7B:t::P:%2C:c:%5B13.01708%2C55.60153%5D%7D%7D%2C%7B:t::F:%2C:p%7B%22id%22:38%2C:mt::%22En%20mark%C3%B6r%22%2C%22popupIsOpen%22:true%7D%2C:g:%7B:t::P:%2C:c:%5B12.97812%2C55.59629%5D%7D%7D%2C%7B:t::F:%2C:p%7B%22id%22:61%2C:mt::%22%22%7D%2C:g:%7B:t:%22LineString%22%2C:c:%5B%5B12.99099%2C55.609%5D%2C%5B12.96713%2C55.60929%5D%2C%5B12.95219%2C55.60289%5D%2C%5B12.95151%2C55.58698%5D%2C%5B12.96404%2C55.57951%5D%2C%5B12.98035%2C55.56961%5D%5D%7D%7D%2C%7B:t::F:%2C:p%7B%22id%22:83%2C:mt::%22%22%7D%2C:g:%7B:t:%22Polygon%22%2C:c:%5B%5B%5B12.93262%2C55.58388%5D%2C%5B12.93022%2C55.57068%5D%2C%5B12.94601%2C55.55952%5D%2C%5B13.01708%2C55.56175%5D%2C%5B13.03493%2C55.57699%5D%2C%5B13.0327%2C55.59115%5D%2C%5B12.98018%2C55.59086%5D%2C%5B12.93262%2C55.58388%5D%2C%5B12.93262%2C55.58388%5D%5D%5D%7D%7D%5D%7D

**Comment by ulfmin** [comment]
Just a map. What should happen?

**Comment by johanlahti** [comment]
Described in English above :)

**Comment by ulfmin** [comment]
Works fine!

**Comment by johanlahti** [comment]
Bra!
