### ISSUE TITLE
Ulfs tester (IE8, IE9, IE10, Nokia Windows Phone

### ISSUE THREAD

**Issue by ulfmin** [getsmap/smap-responsive#146]
IE9: pilar i overlaymeny visas ej
IE9: Ikoner för zooma in och ut mm visas ej

**Comment by ulfmin** [comment]
Utskrift. Kan inte kryssa i boxen teckenförklaring, då skapas ej pdf

Utskrift:
Skala blir troligtvis rätt men inte så bra att visa. Det blir tex 1:1412,  1:2541
Förslag: Kunna välja att lägga till skalstock och att inte visa skalan

**Comment by ulfmin** [comment]
När tänder overlay blir normalt lagret fetstil samt de överliggande nivåerna också.
I IE9 blir det fetstil samt att bakgrund i menyn blir blå

**Comment by ulfmin** [comment]
WiPh-IE: Länk till karta: Kan ej kopiera URL

**Comment by ulfmin** [comment]
WiPh-IE: Kan ej hitta position

**Comment by ulfmin** [comment]
WiPh-IE: Utskrift - Antingen skapas inte pdf eller så går den inte att hitta av annan anledning

**Comment by ulfmin** [comment]
IE9: Förklaringstext i pratbubbla vid Rita syns inte

**Comment by ulfmin** [comment]
IE8: Overlaymeny infälld trots sort fönster:
Overlaymeny mycket svårläst. Blurrig mörk bakgrundsfärg

**Comment by ulfmin** [comment]
IE10 works fine

**Comment by ulfmin** [comment]
Clicking on ÄDP for the Citytunnel. Popup is placed outside the polygon

**Comment by johanlahti** [comment]
IE9: pilar i overlaymeny visas ej
IE9: Ikoner för zooma in och ut mm visas ej

Jag har ändrat mimetype för .woff, .eot och .ttf på servern vilket kanske har löst problemet (det funkar iaf på emulerad IE9. Kan du testa på din IE9 @ulfmin ?

**Comment by johanlahti** [comment]
```Utskrift:
Skala blir troligtvis rätt men inte så bra att visa. Det blir tex 1:1412, 1:2541
Förslag: Kunna välja att lägga till skalstock och att inte visa skalan
```
Skulle en lösning kunna vara att avrunda till närmaste 10-tal eller 100-tal? T ex:

1:1412 -> 1:1410 eller 1:1400
1:2541 -> 1:2540 eller 1:2500

**Comment by johanlahti** [comment]
```
IE9: När tänder overlay blir normalt lagret fetstil samt de överliggande nivåerna också. I IE9 blir det fetstil samt att bakgrund i menyn blir blå.
```
Det ska vara åtgärdat nu. IE9-filter "kletar sig fast" – det tog ett tag innan jag lyckades skriva över alla klasser som använder sådana.

**Comment by johanlahti** [comment]
```WiPh-IE: Länk till karta: Kan ej kopiera URL```
Visst fastslog vi att det är ett Windows Phone-specifikt problem som har att göra med hur text kopieras från ```<input type="text">```-taggar och därför är svårt att göra något åt?

**Comment by johanlahti** [comment]
```WiPh-IE: Kan ej hitta position```
Visst meddelar den då att positionen inte kunde hittas? I så fall är det ingen bugg utan ett misslyckat resultat som meddelas användaren.

**Comment by johanlahti** [comment]
```IE8: Overlaymeny infälld trots sort fönster:
Overlaymeny mycket svårläst. Blurrig mörk bakgrundsfärg```
Förhoppningsvis är funktionaliteten i IE8 "åtkomlig" iaf enligt citatet i WAG:n:
```
For Internet Explorer 7 and 8 on desktop versions of Windows, cosmetic flaws are accepted, but the information must be findable and readable for the user.
```
Däremot uppfyller den knappast IE7… då får vi nog nedgradera alla bibliotek eller bygga om koden så vi använder t ex Requirejs för att läsa in skripten.
