### ISSUE TITLE
Add info to RedirectClick for mobile users

### ISSUE THREAD

**Issue by peterahlstrom** [getsmap/smap-responsive#149]
Desktop user get a tooltip telling them to click on the map, but mobile user are left on their own. Suggesting that we add a popover or similar with the same info.

**Comment by johanlahti** [comment]
:+1:

**Comment by johanlahti** [comment]
To make it even more clear one can add the ```active``` class to the button which gives it a "pressed-down"-look.

**Comment by johanlahti** [comment]
For touch devices I add a div at the bottom of the screen using the same text as for the cursor tooltip. The div is removed on deactivate.
