### ISSUE TITLE
Print: conditions popover disappear immediatly on mobile

### ISSUE THREAD

**Issue by peterahlstrom** [getsmap/smap-responsive#157]
When touching the disabled "Create image"-button, the popover which appears at the conditions checkbox closes immediatly on Chrome for Android (Nexus 4).

**Comment by peterahlstrom** [comment]
Same problem with Safari, iOS 8.1.3, iPhone5S

**Comment by johanlahti** [comment]
The ```.focus()``` in ```self.conditionsCheckbox.popover('show').focus();``` is the bad guy here.
Do we need the focus? Otherwise, the solution would be to remove it.

**Comment by peterahlstrom** [comment]
I'll look into it!

**Comment by peterahlstrom** [comment]
Tested on same mobile devices and seems to work fine now.

**Comment by johanlahti** [comment]
:clap: :cactus:

**Comment by peterahlstrom** [comment]
Thanks for the cactus, it means alot to me...

**Comment by johanlahti** [comment]
It should. Cactuses are amazing plants. And I just discovered it's easy to find other icons here: http://www.emoji-cheat-sheet.com/  :snail:
