### ISSUE TITLE
IE10/11 placeholder bug affects MeasureDraw

### ISSUE THREAD

**Issue by johanlahti** [getsmap/smap-responsive#160]
There is a bug in IE10/11 which converts the placeholder text in ```<textarea>``` tags into a real value which affects MeasureDraw.

**Comment by johanlahti** [comment]
Solved by explicitly removing the text in the popup if browser is IE10/11. Surprised such bugs can slip through in a big browser like IE… at the same time not surprised.

**Comment by peterahlstrom** [comment]
:smiley:

**Comment by johanlahti** [comment]
:smiley:
