### ISSUE TITLE
Öppen fråga för diskussion i Malmö: Kan/Vill vi bygga ut publika Stadsatlas till intern atlas?

### ISSUE THREAD

**Issue by johanlahti** [getsmap/smap-responsive#161]
Den nya atlasen har fått mycket positiv respons då den är mycket modernare än den gamla, liksom den nuvarande Verksamhetsatlasen. Om det skulle innebära ganska lite jobb – skulle det då vara önskvärt att bygga ut smap-responsive med de funktioner som fattas för att den ska täcka behoven i Verksamhetsatlasen?

Tanken är i så fall att vi skulle lägga till dessa "verksamhetsfunktioner" när användaren befinner sig inom Malmö stads nät.

Vad jag kan se är det i nuläget följande som fattas:

- Verktyg för transparens
- Fler lager
- Ändra sökkälla för sökningar som sker via Malmö-stad-dator
- Registrering av NBK (kod finns redan)
- Skapa lägeskarta
- Sök i ÖP

Det mest utvecklingskrävande skulle vara Sök i ÖP (även kallad Blixten). Å andra sidan finns det säkert intresse från Planavdelningen att uppdatera den. En grov uppskattning är att det skulle ta ca en kommunarbetarmånad (inkl. möten och annat) att utveckla detta.

**Comment by ulfmin** [comment]
Frågan bör väl rikta sig till en större grupp

Från: Johan Lahti [mailto:notifications@github.com]
Skickat: den 27 februari 2015 11:32
Till: getsmap/smap-responsive
Kopia: Ulf Minör
Ämne: Re: [smap-responsive] Öppen fråga för diskussion i Malmö: Kan/Vill vi bygga ut publika Stadsatlas till intern atlas? (#161)


Assigned #161<https://github.com/getsmap/smap-responsive/issues/161> to @ulfmin<https://github.com/ulfmin>.

**Comment by johanlahti** [comment]
Tycker jag också. Vi kan diskutera det på nästa möte.

**Comment by karl-magnus** [comment]
Skulle vi förresten göra lite undersökningar på geoAdmin och OL3?

**Comment by johanlahti** [comment]
Ja, det borde vi göra rätt snart. På längre sikt är jag (med nuvarande kunskap) övertygad om att OL3 är rätt väg att gå för en intern atlas – åtminstone med de verktygen som föreslagits för Malmös nya interna atlas (mMap). För att replikera nuvarande verksamhetsatlas i Malmö är det dock inte så mycket mer som kvarstår, vad jag kan se. Frågan är – är det värt att lägga den tiden om vi ändå ska utveckla en ny verksamhetsatlas på sikt (kanske 1,5 - 2 år)?

**Comment by karl-magnus** [comment]
För vår del tror jag det inte är aktuellt just nu. Jag(vi) har lagt ner rätt många timmar på att fixa till en saker i 4.3 som skulle behövas göras om i ett ramverk som jag inte är så van vid. Skulle kännas bättre att lägga arbete på en ny på lite längre sikt. Men det är kanske ett dåligt argument.

**Comment by johanlahti** [comment]
Ja och ni har väl ännu mer verktyg att porta i så fall. Det är bra att vi diskuterar frågan iaf så vi har alternativen klara för oss. Det finns alltid en risk att större projekt som dessa drar ut på tiden och då kan det vara skönt att ha en lite modernare verksamhetsatlas i ryggen. Å andra sidan, i ett sånt scenario minskar pressen på att få det klart, vilket kan vara negativt också.

**Comment by peterahlstrom** [comment]
Detta är som Ulf mycket riktigt säger något som behöver dras i en större grupp, men det här är en bra början.
Mina tankar: Går det på att ca en månad skapa en atlas med en livslängd på 1-2 år är det klart värt det. Den minskade pressen det ger kan i bästa fall också ge en bättre ny verksamhetsatlas. I vilket fall borde det bli bättre för användaren som inte behöver uppleva ett så stort hopp mellan det gamla och nya.
