### ISSUE TITLE
Support for e.g. ESRI Feature service

### ISSUE THREAD

**Issue by johanlahti** [getsmap/smap-responsive#172]
Give support for ESRI's web service or other services which do not follow WFS standards.

**Comment by cleberar38** [comment]
## Suggestion
Link:
https://github.com/Esri/esri-leaflet

**Comment by johanlahti** [comment]
esri-leaflet's FeatureLayer was not working when we tested so we used our own L.GeoJSON.WFS layer which worked almost out of the box. Unfortunately ESRI's Feature Service (at least the one we tested from Helsingborg) does not return text as UTF-8 so "åäö" becomes "???".

I hereby close the issue…
