### ISSUE TITLE
Improve Fullscreen plugin

### ISSUE THREAD

**Issue by peterahlstrom** [getsmap/smap-responsive#180]
Add the following options:
* open large map in same window (for use in iframe)
* open large map in new tab (for use in iframe)
* show map in fullscreen

**Comment by johanlahti** [comment]
I'm adding one:
- Don't display button if fullscreen is not supported :computer:

**Comment by johanlahti** [comment]
Not working in IE11. Results in an unrendered page (white).

**Comment by peterahlstrom** [comment]
Added workaround to solve IE11-problem, possibly caused by this known bug: https://connect.microsoft.com/IE/feedback/details/814527/ie11-iframes-body-offsetwidth-incorrect-when-iframe-is-in-full-screen-mode
