### ISSUE TITLE
IE11 gives "not supported browser" warning

### ISSUE THREAD

**Issue by johanlahti** [getsmap/smap-responsive#192]

**Comment by peterahlstrom** [comment]
This seems to be more of a generic bug than a Error reporting app specific problem.
Move to different milestone?

**Comment by johanlahti** [comment]
Indeed a good idea. Perhaps v1.3 milestone. Then we should look through that milestone to see what we can manage before the mMap project. Less important issues should be moved to future milestone.

**Comment by johanlahti** [comment]
Anyone managed to reproduce this bug?

**Comment by johanlahti** [comment]
I close, open again if it can be verified.
