### ISSUE TITLE
Allow specifying fallback directories for config parameter

### ISSUE THREAD

**Issue by johanlahti** [getsmap/smap-responsive#212]
**Previously:**

```config=mymap.js```  => Try to find it here: ```configs/mymap.js or dist/configs/mymap.js```  (depending on prod or dev mode). The paths are hard-coded.

**The desired outcome of this ticket:**

```config=mymap.js``` => Try to find it here (iterate all dirs): ```smap.core.mainConfig.configDirs {Array} + mymap.js```
config=myconfigs/mymap => Try to find it here (iterate all dirs): ```smap.core.mainConfig.configDirs {Array} + mymap.js```

**Comment by johanlahti** [comment]
Also, if config was found in a different directory than the one specified, listen for ```createparams``` event and set the the config to the corrected value, so that next time the map is shared the correct path is given from start and we don't need to try the fallback paths.

**Comment by peterahlstrom** [comment]
:thumbsup:
