### ISSUE TITLE
Clone and install dependencies Problem

### ISSUE THREAD

**Issue by mohammadamin46bd** [getsmap/smap-responsive#217]
It seems to have some problem with Clone and install dependencies process.
I think the repository doesn't contain some of the necessary folders or files to currectly run the task from gulpfile.js file.

**Comment by johanlahti** [comment]
Are you sure it's not related to the privileges associated with the checkout folder? It could also be that you need to clean the npm and bower cache: `bower cache clean && npm cache clean`.

I tried myself using the following command (the one described in the intro but merged into one):

`svn co https://github.com/getsmap/smap-responsive/trunk smap-test && cd smap-test && npm install && bower install && gulp full`

and its working OK for me. Note that if you use `sudo` at some point in the beginning and don't use it in a later command, it might stop the installer from writing to a folder which can cause the install to break.

**Comment by mohammadamin46bd** [comment]
I have tried with the above but have the same result. 
I have attached a file called cloneProcess.txt on the attachment where it shows the Clone and install dependencies process.

[cloneProcess.txt](https://github.com/getsmap/smap-responsive/files/137766/cloneProcess.txt)

After that process I have got the below files and folders (on GitHub link 1: uploaded them to GitHub to show what that process has downloaded and processed) on my machine’s local repository from https://github.com/getsmap/smap-responsive/trunk.


GitHub link 1: https://github.com/mohammadamin46bd/Test/tree/master/smap-responsive

So when I try to run the below link it shows lots of errors:
 http://localhost/smap-responsive/dev.html?config=examples/configs/myconfig.js
or 
http://localhost/smap-responsive/dist/index.html ?config=../examples/configs/myconfig.js

The errors are for examples $ not defined, cannot read property 'extent' of undefined, cannot read property 'core' of undefined from different files (lib.js and others).

Is it something that it is needed to readjust the html (http://localhost/smap-responsive/dev.htm or http://localhost/smap-responsive/dist/index.html) files by adding the lacked js files or others?

Or something goes wrong on Clone and installs dependencies process?

Thanks in advance.

**Comment by johanlahti** [comment]
I checked your attached log and I see that it stops on `malmo_shared_assets`. I don't know why that dependency has been added (probably a mistake). It seems that access to that resource is limited if you are outside of Malmö stad and that's why your bower install fails – which leads to the above mentioned errors. Surprisingly it has worked for others, e.g. in Lund and Tomelilla kommun… However, it could also be that this limitation has been added recently by the malmoasset creators/Malmö IT.).

Please try again with the latest code!

**Comment by mohammadamin46bd** [comment]
Thanks for the information and I will try with the latest code.
Thanks in advance.

**Comment by mohammadamin46bd** [comment]
It works now. Bower install fails when I was trying to run it from inside the corporate network. But it works when I have tried it from outside the corporate network. It might be a firewall setting from our IT that doesn’t allow executing some specific command from internal network.
 
This problem is solved and this issue can be closed. Thanks for your help.

**Comment by johanlahti** [comment]
Good job from the Kristianstad IT – should not encourage too much cooperation between municipalities :smile:

Great it's working now! I close the issue.
