### ISSUE TITLE
"Don't show again"-checkbox in Info dialog

### ISSUE THREAD

**Issue by johanlahti** [getsmap/smap-responsive#227]

**Comment by johanlahti** [comment]
Excellent suggestion by @peterahlstrom to add an expiration date to the localStorage (like for cookies in general) so that the dontShowAgain checkbox expires after a certain date (e.g. 30 days). To this I will also add a global expiry date option `dateLastUpdated` which will make all dontShowAgain variables obsolete if they were registered before this date. Thus, even better than simply a cookie with an expiration date.

**Comment by peterahlstrom** [comment]
:thumbsup:

**Comment by johanlahti** [comment]
Ready for test (I'm closing).
