### ISSUE TITLE
Highlight feature fails popup, new parser needed?

### ISSUE THREAD

**Issue by jakelund** [getsmap/smap-responsive#231]
**Using QGIS server. Popup fails when using highlight on click.**
selectOptions: {
					service: "WFS",
					request: "GetFeature",
					outputFormat: "GeoJSON",
					url: "http://193.17.67.229/qgis/lund/vspu-test/qgis_mapserv.fcgi",
					srs: "EPSG:3008",
					layers: "Kavlingean-avrinningsomrade-del",
					info_format:"application/json"
					 }

**Response without using highlight on select feature, popup works:**
GetFeatureInfo results

Layer 'Kavlingean-avrinningsomrade-del'
Feature 27
id = '27'
dn = '56'
areakm2 = '35.42'
areauppkm2 = 'NULL'
totareakm2 = 'NULL'
namn = 'NULL'

**Response using highlight, popup fails:**
{"type": "FeatureCollection",
 "bbox": [ 136501.11528311, 6176994.93742121, 138231.96549739, 6178712.10840564],
 "features": [
  {"type": "Feature",
   "id": "Kavlingean-avrinningsomrade-del.27",
 "bbox": [ 132955.92390435, 6172934.97548381, 142241.32070863, 6180830.41445169],
  "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ [...] ] ] ] },
   "properties": {
    "id": "27"
   ,"dn": 56
   ,"areakm2": 35.42
   ,"areauppkm2": 0
   ,"totareakm2": 0
   ,"namn": ""
   }  } ]}

**Comment by johanlahti** [comment]
With the last commit this works for me using these selectOptions:

```
selectOptions: {
	service: "WFS",
	request: "GetFeature",
	// outputFormat: "GeoJSON",
	url: "http://localhost/lundqgis/lund/vspu-test/qgis_mapserv.fcgi",
	srs: "EPSG:3008",
	layers: "Kavlingean-avrinningsomrade-del",
	info_format: "text/plain"
},

```
Remember to set popup to extract some existing attributes, such as:
```
popup: '<div>${areakm2}</div>',
```

**Comment by johanlahti** [comment]
I should add that requesting with `info_format: application/json` is not supported according to the response I get from your QGIS server instance.

**Comment by johanlahti** [comment]
I close – reopen if needed.

**Comment by jakelund** [comment]
Ok, can't try new build for a while, but thanks anyway!
