### ISSUE TITLE
Goto XY feature request

### ISSUE THREAD

**Issue by jakelund** [getsmap/smap-responsive#232]
Would like to input coordinates and have the map place a pin there. Support for several coordinate systems preferable. The foundation should be there considering using search on parcels uses coordinates to place a pin on that parcel. Panning a pin to the right coordinates possible today, but not really user friendly.

No such feature at hitta.se, eniro.se or lantmäteriet.se. Would be great to add to smap.

**Comment by johanlahti** [comment]
Thanks for the suggestion. I think what you describe is already implemented, using the `xy` web parameter like this: `xy={lon},{lat},{popup text},{EPSG number}`. For instance:
```
http://localhost/smap-responsive/dev.html?xy=13.0,55.6   // assuming EPSG:4326
http://localhost/smap-responsive/dev.html?xy=13.0,55.6,,4326   // setting projection explicitly
http://localhost/smap-responsive/dev.html?xy=13.0,55.6,Hej,4326  // setting a popup text
```

**Comment by johanlahti** [comment]
Reopen this issue if you are missing something regarding this functionality.
